# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gent' do
  use_frameworks!



  # Pods for Gent
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Stripe'
pod 'Alamofire'
pod 'SwiftyJSON'

pod 'ReachabilitySwift'

  target 'GentTests' do
    inherit! :search_paths
     end
end

