# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gent' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gent
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Database'

pod 'Stripe'
pod 'Alamofire'
pod 'KeychainSwift'

  target 'GentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GentUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
