# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gent' do
  use_frameworks!

# Pods for Gent
pod 'Firebase/Core', '~> 3.15.0'
pod 'Firebase/Database', '~> 3.15.0'
pod 'Firebase/Auth', '~> 3.15.0'
pod 'Stripe'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'ReachabilitySwift'

end

